{% set name = "kipoiseq" %}
{% set version = "0.2.5" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "250e1ce481d7e5537476851882bcb1cec3bf3757a58a01605c143c2ab2d39824" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'


build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - kipoi >=0.5.5
    - pybedtools
    - pyfaidx
    - genomelake
    - numpy
    - pandas
    - tqdm
    - gffutils
  run:
    - python
    - kipoi >=0.5.5
    - kipoi-conda
    - pybedtools
    - pyfaidx
    - genomelake
    - numpy
    - pandas
    - tqdm
    - gffutils

test:
  imports:
    - kipoiseq
    - kipoiseq.dataloaders
    - kipoiseq.transforms
  requires:
    # - bumpversion
    # - coveralls
    # - cython
    # - epc
    # - jedi
    # - keras
    # - pybedtools
    # - pytest >=3.3.1
    # - pytest-cov
    # - pytest-pep8
    # - pytest-xdist
    # - scikit-learn
    # - tensorflow
    # - wheel

about:
  home: https://github.com/kipoi/kipoiseq
  license: MIT license
  license_family: MIT
  summary: 'kipoiseq: sequence-based data-laoders for Kipoi'
  description: 'kipoiseq: sequence-based data-laoders for Kipoi'
  doc_url: 'https://kipoi.org/kipoiseq/'

extra:
  recipe-maintainers:
    - Avsecz
