{% set name = "scanpy" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

source:
  url: https://github.com/theislab/scanpy/archive/{{ version }}.tar.gz
  sha256: 1b2fdb5769deac2d31905f156802bc4a7f4df3ee46b1eaa9e479af2162fb1c12

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - seaborn
    - scikit-learn
    - statsmodels
    - importlib-metadata
    - numba
    - python-igraph
    - louvain
    - 'anndata >=0.6.10'
    - 'matplotlib >=2.2'
    - 'pandas >=0.21'
    - scipy <1.3
    - h5py
    - pytables
    - networkx
    - natsort
    - tqdm
    - umap-learn

test:
  imports:
    - scanpy

about:
  home: https://scanpy.readthedocs.io/en/latest/
  license: BSD-3
  summary: Single-Cell Analysis in Python. Scales to >1M cells. 

extra:
  identifiers:
    - doi:10.1186/s13059-017-1382-0
