{% set version = "0.3.0" %}
{% set github = "https://github.com/acidgenomics/brio" %}

package:
  name: r-brio
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 48c7635083fb5b78926a1d249feac1f0c7aff6982fe6273747c3405a00f7ffc8

build:
  number: 0
  noarch: generic

requirements:
  host:
    - r-base
    - r-bioverbs >=0.2.0
    - r-goalie >=0.2.18
    - r-transformer >=0.2.0
    - bioconductor-genomicranges >=1.36.0
    - bioconductor-rtracklayer >=1.44.0
    - bioconductor-s4vectors >=0.22.0
    - bioconductor-singlecellexperiment >=1.6.0
    - bioconductor-summarizedexperiment >=1.14.0
    - r-curl >=1.95
    - r-data.table >=1.12
    - r-jsonlite >=1.6
    - r-matrix >=1.2
    - r-r.utils >=2.9
    - r-readr >=1.3
    - r-rio >=0.5
    - r-stringr >=1.4
    - r-tibble >=2.1
    - r-yaml >=2.2

  run:
    - r-base
    - r-bioverbs >=0.2.0
    - r-goalie >=0.2.18
    - r-transformer >=0.2.0
    - bioconductor-genomicranges
    - bioconductor-rtracklayer >=1.44.0
    - bioconductor-s4vectors
    - bioconductor-singlecellexperiment
    - bioconductor-summarizedexperiment
    - r-curl >=1.95
    - r-data.table >=1.12
    - r-jsonlite >=1.6
    - r-matrix >=1.2
    - r-r.utils >=2.9
    - r-readr >=1.3
    - r-rio >=0.5
    - r-stringr >=1.4
    - r-tibble >=2.1
    - r-yaml >=2.2

test:
  commands:
    - $R -e "library('brio')"

about:
  home: https://brio.acidgenomics.com/
  dev_url: "{{ github }}"
  license: MIT
  summary: Biological R input/output.

extra:
  recipe-maintainers:
    - mjsteinbaugh
