{% set version = "0.11.1" %}
{% set github = "https://github.com/acidgenomics/basejump" %}

package:
  name: r-basejump
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 4fe2a862a92bc6c0c6f9cea94e5bb15a7d2c26f4853a68703825a127a689c295

build:
  number: 0
  noarch: generic

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-bioverbs >=0.2.0
    - r-brio >=0.3.0
    - r-freerange >=0.2.0
    - r-goalie >=0.2.19
    - r-syntactic >=0.2.0
    - r-transformer >=0.2.0
      # Pinning against Bioconductor 3.9.
    - bioconductor-biobase >=2.44.0
    - bioconductor-biocgenerics
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-singlecellexperiment >=1.6.0
    - bioconductor-summarizedexperiment >=1.14.0
    - r-dplyr >=0.8
    - r-knitr >=1.22
    - r-magrittr >=1.5
    - r-matrix >=1.2
    - r-matrix.utils >=0.9
    - r-matrixstats >=0.54
    - r-purrr >=0.3
    - r-readr >=1.3
    - r-reshape2 >=1.4
    - r-rlang >=0.4
    - r-sessioninfo >=1.1
    - r-stringr >=1.4
    - r-tibble >=2.1.1
    - r-tidyr >=0.8
    - r-tidyselect >=0.2
    # These requirements are not in package DESCRIPTION.
    - r-assertthat >=0.2.1
    - r-glue >=1.3.1
    - r-rcpp >=1.0.2

  run:
    - r-base
    - r-bioverbs >=0.2.0
    - r-brio >=0.3.0
    - r-freerange >=0.2.0
    - r-goalie >=0.2.19
    - r-syntactic >=0.2.0
    - r-transformer >=0.2.0
      # Pinning against Bioconductor 3.9.
    - bioconductor-biobase >=2.44.0
    - bioconductor-biocgenerics
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-singlecellexperiment >=1.6.0
    - bioconductor-summarizedexperiment >=1.14.0
    - r-dplyr >=0.8
    - r-knitr >=1.22
    - r-magrittr >=1.5
    - r-matrix >=1.2
    - r-matrix.utils >=0.9
    - r-matrixstats >=0.54
    - r-purrr >=0.3
    - r-readr >=1.3
    - r-reshape2 >=1.4
    - r-rlang >=0.4
    - r-sessioninfo >=1.1
    - r-stringr >=1.4
    - r-tibble >=2.1.1
    - r-tidyr >=0.8
    - r-tidyselect >=0.2
    # These requirements are not in package DESCRIPTION.
    - r-assertthat >=0.2.1
    - r-glue >=1.3.1
    - r-rcpp >=1.0.2

test:
  commands:
    - $R -e "library('basejump')"

about:
  home: https://basejump.acidgenomics.com/
  dev_url: "{{ github }}"
  license: MIT
  summary: Base functions for bioinformatics and R package development.

extra:
  recipe-maintainers:
    - mjsteinbaugh
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
